config/routes.rb
Rails.application.routes.draw do
  # resources :doses
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [:new, :create, :destroy]
  end
  # resources :ingredients

  root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, :cocktail_id, :ingredient_id, presence: true
  validates_uniqueness_of :cocktail, scope: :ingredient
  # validates [:cocktail, :ingredient], uniqueness: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def edit
    @cocktail = Cocktail.new
  end

  def update
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    Cocktail.destroy(params[:id])
    redirect_to cocktails_path
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def index
  end

  def show
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy

  end
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def show
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/edit.html.erb
<h1>Cocktails#edit</h1>
<p>Find me in app/views/cocktails/edit.html.erb</p>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: url('https://images.unsplash.com/photo-1468072114808-903e572b8ead?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1866&q=80');">
  <div class="banner-content">
    <h1>Mister Cocktail</h1>
    <br>
<%= link_to new_cocktail_path, { class: "btn btn-primary" } do %>
<%= "Create A Cocktail" %>
<% end %>
  </div>
</div>

<div class="container">
  <div class="row">

    <% @cocktails.each do |cocktail| %>
    <%= link_to cocktail_path(cocktail) do %>
    <div class="col-xs-12 col-sm-4 col-lg-3">
      <div class="card" style="background-image: url('https://images.unsplash.com/photo-1509669803555-fd5edd8d5a41?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80');">
       <span class="card-description"> <h2><%= cocktail.name %></h2></span>
     </div>
     <% end %>
   </div>
   <% end %>
 </div>
</div>

app/views/cocktails/new.html.erb
<p>Cocktails#new</p>
<p>Find me in app/views/cocktails/new.html.erb</p>
<h2>Create a new Cocktail:</h2>
<%= simple_form_for [@cocktail] do |f| %>
<%= f.input :name %>
<%= f.submit "Create new Cocktail", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: url('https://images.unsplash.com/photo-1468072114808-903e572b8ead?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1866&q=80');">
  <div class="banner-content">
    <h1> <%= @cocktail.name %> </h1>
  </div>
</div>
<div class="form-container">
  <div class="form-center">
    <h2> Ingredients </h2>
    <ul>
      <% @cocktail.doses.each do |dose| %>
      <li><%= dose.description %> <%= dose.ingredient.name %>
      </li>
      <% end %>
    </ul>

    <h2>Add an Ingredient and Dose</h2>
    <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %> <!-- # simple form ermöglich Zugriff über dose.ingredient -->
    <%= f.submit "Create Dose", class: "btn btn-primary" %>
    <% end %>
    <p><%= link_to "Back to index", cocktails_path %></p>
    <p><%= link_to "Delete Cocktail", cocktail_path(@cocktail), method: "delete" %></p>
  </div>
</div>

<%= cl_image_tag("mvomujbluhjwzvw4disc",
      width: 400, height: 300, crop: :fill) %>

app/views/cocktails/update.html.erb
<h1>Cocktails#update</h1>
<p>Find me in app/views/cocktails/update.html.erb</p>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/edit.html.erb
<h1>Doses#edit</h1>
<p>Find me in app/views/doses/edit.html.erb</p>

app/views/doses/index.html.erb
<h1>Doses#index</h1>
<p>Find me in app/views/doses/index.html.erb</p>

app/views/doses/new.html.erb
<h2>Create a new Dose:</h2>
<%= @cocktail.name %>
<%= simple_form_for [@cocktail, @dose] do |f| %>
<%= f.input :description %>
<%= f.association :ingredient %> <!-- # simple form ermöglich Zugriff über dose.ingredient -->
<%= f.submit "Create Dose", class: "btn btn-primary" %>
<% end %>
<%= link_to "Back to index", cocktails_path %>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

app/views/doses/update.html.erb
<h1>Doses#update</h1>
<p>Find me in app/views/doses/update.html.erb</p>

app/views/ingredients/index.html.erb
<% @ingredients.each do |ingredient| %>
<ul>
  <li><%= ingredient.name %></li>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
</body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>